### ISSUE TITLE
Assignment 5: Completed for Review

### ISSUE THREAD

**Issue by chbackstrom** [chbackstrom/Assignment-5#1]
My Assignment-5 repository includes a .Rmd file (in the "figures" folder, as instructed) including two exploratory iterations of a length vs. weight figure (by fish sex) and an expository figure enhancing the presentation according to concepts covered in lecture. Please let me know if you have any questions or issues accessing the file(s).

**Comment by mdscheuerell** [comment]
Great job with these figures, Callum! And I really appreciate your attention to concepts covered in class and in the accompanying materials.
